diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["fl_joint", "bl_joint"]
    right_wheel_names: ["fr_joint", "br_joint"]
    wheel_separation: 0.208
    wheel_radius: 0.0425
    cmd_vel_timeout: 0.25
    publish_rate: 50

controller_manager:
  ros__parameters:
    update_rate: 50
