controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints: ["fl_joint", "fr_joint", "bl_joint", "br_joint"]

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["bl_joint", "fl_joint"]
      right_wheel_names: ["br_joint", "fr_joint"]
      wheel_separation: 0.218
      wheel_radius: 0.0425
      cmd_vel_timeout: 0.25
      publish_rate: 50
      update_rate: 1000
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
