controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.15
      max_vel_x: 0.3
      min_vel_theta: 1.5
      max_vel_theta: 2.0
      acc_lim_x: 0.5
      acc_lim_theta: 2.0

      # Critic plugins
      critic_plugins: ["ObstacleCritic", "GoalAlignCritic", "PathAlignCritic"]

    # Parameters for each critic
    ObstacleCritic:
      plugin: "dwb_critics::ObstacleFootprint"
      footprint_model_type: "point"
      inflation_dist: 0.2

    GoalAlignCritic:
      plugin: "dwb_critics::GoalAlign"

    PathAlignCritic:
      plugin: "dwb_critics::PathAlign"
