amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 200
    max_particles: 2000

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.15      # min forward speed (m/s)
      max_vel_x: 0.3      # max forward speed (m/s)
      min_vel_theta: 1.5   # min rotation speed (rad/s)
      max_vel_theta: 2.0   # max rotation speed (rad/s)
      acc_lim_x: 0.5       # m/s^2
      acc_lim_theta: 2.0   # rad/s^2
